spring:
  application:
    name: crm

  datasource:
    url: jdbc:postgresql://localhost:5432/crmaster
    username: postgres
    password: '1234'
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG